steps:
  - name: golang
    env: [
        'GO111MODULE=on',
        'GOPROXY=https://proxy.golang.org,direct',
        'GOOS=linux',
        'GOARCH=amd64'
    ]
    args: ['go', 'build', './cmd/main/main.go']
artifacts:
  objects:
    location: 'gs://gcp-example-1290/' # Change this to match your storage
    paths: ['main']
